### PR TITLE
Update to latest Youtube Downloader version

### PR DESCRIPTION
**Pull request by DeXteRrBDN**
This fixes "ERROR: Signature extraction failed" issue

### CODE REVIEW

**Comment by mxpv** [comment]
@DeXteRrBDN Thanks!

**Comment by DeXteRrBDN** [comment]
You're welcome :)

How can I create release v2.0.7  to be able to download latest version as a docker image?

**Comment by mxpv** [comment]
Done https://github.com/mxpv/podsync/releases/tag/v2.0.7

**Comment by DeXteRrBDN** [comment]
Nice!! Thanks :D

This also solved my issue with "only audio" conversions 👏

**Pull request merged**
