### PR TITLE
Support S3-compatible provider as storage backend

### LINKED ISSUE #159: Feature request: crawler mode without web server
I'm using S3 to host files generated by podsync, and it would be great if podsync can be executed like a crawler, which generates the data and then exits.

That way, 

- I can avoid exposing another port of my server to Internet
- podsync does not need to be running in background all the time (I'll use cron to excute podsync and transfer the data)

I know I can use firewall to block access to the port exposed by podsync, but it's always nice IMHO to have less firewall rules and running-in-background processes.

### PR DESCRIPTION
**Pull request by Contextualist**
Currently, this is a working implementation, but still work and discussion are needed. This resolves #159 and achieve part of the goals in #180.

To try this out, set a config as the following:
```toml
[server]
hostname = "https://example-bucket-name.s3-website-us-west-2.amazonaws.com"

[storage]
  type = "s3"
  [storage.s3]
  endpoint = "https://s3.us-west-2.amazonaws.com"
  region = "us-west-2"
  bucket = "example-bucket-name"

# ...
```

And set the access key and secret in environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (credential should also works per aws-sdk-go's documentation, but I haven't tried it out).

Optional: use CLI arg `--headless` to quit after first round of updates.

To be discussed:

- ~~Should `--update-once` be a config entry instead? Should we rename it?~~ Renamed to `--headless`
- ~~Where should the `s3` config entry be located?~~ In the new `storage` config section
- Default values for the `s3` config entries?
- Should the `fs.Storage` interface include `http.FileSystem`?
- ~~Dependency [aws/aws-sdk-go](https://github.com/aws/aws-sdk-go) is quite heavy (compiled binary size is increased from 4MB to 22MB); should we use a lighter implementation for the S3 API (e.g. [rhnvrm/simples3](https://github.com/rhnvrm/simples3))?~~ No change

To do:

- [x] tests for `fs.S3`
- [x] documentation (README, example config)

Any other discussions are welcome. I hope this PR can contribute some ideas on the S3 backend. If you already have something better, feel free to close this in favor of another PR!

### CODE REVIEW

**Comment by mxpv** [comment]
This is awesome!
Could you please run `go mod tidy` to update go mod files, to make CI happy?
Other then that, LGTM.

**Comment by mxpv** [comment]
> Should --update-once be a config entry instead? Should we rename it?

How about `headless` mode? This one will be useful when running in AWS Lambda, for instance.

> Where should the s3 config entry be located?

I'd define `storage_type=local|s3`

> Dependency [aws/aws-sdk-go](https://github.com/aws/aws-sdk-go) is quite heavy (compiled binary size is increased from 4MB to 22MB); should we use a lighter implementation for the S3 API (e.g. [rhnvrm/simples3](https://github.com/rhnvrm/simples3))?

I'd stick with official AWS SDK

**Comment by Contextualist** [comment]
> I'd define storage_type=local|s3

Do you mean something like this?
```toml
storage_type = "local" # default value if omitted

[server]
hostname = "https://example-host.com"
port = 8080
data_dir = "/data/podsync/"

# ...
```

```toml
storage_type = "s3"

[server]
hostname = "https://example-bucket-name.s3-website-us-west-2.amazonaws.com"

[s3]
endpoint = "https://s3.us-west-2.amazonaws.com"
region = "us-west-2"
bucket = "example-bucket-name"

# ...
```

**Comment by mxpv** [comment]
May be something like
```toml
[storage]
type="local|s3"

  [storage.s3]
  ...
  [storage.local]
  ...
```

WDYT?

**Comment by Contextualist** [comment]
What would be under `storage.local`? If we move `server.data_dir` to `storage.local.data_dir`, we introduce a backward incompatibility.

**Comment by Contextualist** [comment]
I think `storage.local.data_dir` makes more sense in the current model anyway. Maybe we could deprecate `server.data_dir`: emit a warning to the user and encourage the following settings
```toml
[storage]
# type="local" by default
  [storage.local]
  data_dir = "/data/podsync/"
```
and remove `server.data_dir` in the future. These changes will be transparent to the Docker users.

**Comment by mxpv** [comment]
Sounds good to me.

**Comment by Contextualist** [comment]
Everything is ready except for documentation updates (README.md, config.toml.example, cloud_formation.yml). Since the `storage` section is a major change to the config, should we postpone the documentation change until the next release?

**Comment by mxpv** [comment]
Next release will include these changes, so it’s fine to include documentation updates too.

**Comment by Contextualist** [comment]
Ok, done!

**Comment by mxpv** [comment]
Thanks!

**Comment by mxpv** [comment]
Next release will include these changes, so it’s fine to include documentation updates too.

**Pull request merged**
