### PR TITLE
SelfUpdate for youtube-dl #119

### PR DESCRIPTION
**Pull request by Rpsl**
In the right way we need make update by cron with lock and stop downloader goroutines.

I can't do it at the moment, but i think we can call selfupdate on start. 
Until selfupdate by timer not implemented we can fix it by stop and start again 🤷‍♂️

### CODE REVIEW

**Comment by dop251** [comment]
I think this should be made optional in case there is an alternative update mechanism. It may be hard to believe but not everyone uses docker these days :)

**Comment by Rpsl** [comment]
@dop251 yep. you right. 
when i was make that i don't think about not docker version and possible permission troubles.

at now i think selfupdate and any another version management must be outside application logic. for self i use that bash script in cron

```
#!/bin/sh

if [  "$(docker ps -a | grep podsync)" ]; then
	docker exec podsync  youtube-dl --update --verbose
fi
```

**Comment by Rpsl** [comment]
i revert code, but has left changes in dockerfile

**Comment by mxpv** [comment]
I've added optional flag to enable youtube-dl self updated.

**Pull request merged**
